[project]
name = "pychargecloud"
version = "0.0.1"
dependencies = [
    "aiohttp",
    "yarl",
    "pydantic",
]
authors = [
    { name="functionpointer", email="suspendfunction@gmail.com" }
]
description = "Access public ev charger information via chargecloud.de"
requires-python = ">=3.10"

[project.urls]
"Homepage" = "https://github.com/functionpointer/pychargecloud"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"